In [32]:
import pandas as pd
import numpy as np

In [33]:
df=pd.read_csv("data/Yelp_Reviews.csv")
df.head()

,Unnamed: 0,business_id,cool,date,funny,review_id,stars,text,useful,user_id
0,1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5.0,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g
1,2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1.0,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g
2,4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5.0,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g
3,5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,NaN,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g
4,10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5.0,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2610 entries, 0 to 2609
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   2610 non-null   int64
 1   business_id  2610 non-null   object
 2   cool         2608 non-null   object
 3   date         2610 non-null   object
 4   funny        2610 non-null   int64
 5   review_id    2610 non-null   object
 6   stars        2607 non-null   float64
 7   text         2610 non-null   object
 8   useful       2610 non-null   int64
 9   user_id      2610 non-null   object
dtypes: float64(1), int64(3), object(6)
memory usage: 204.0+ KB

In [35]:
#Lambda function
multiply = lambda x: x*2
print(multiply(4))

8

In [43]:
df["text"].apply(lambda text:len(text.split()))

0        58
1        30
2        30
3        82
4        32
       ...
2605     61
2606     43
2607     79
2608    185
2609     42
Name: text, Length: 2610, dtype: int64

In [46]:
df["review.length"] = df["text"].apply(lambda text:len(text.split()))
df.head()

,Unnamed: 0,business_id,cool,date,funny,review_id,stars,text,useful,user_id,review.length
0,1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5.0,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g,58
1,2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1.0,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g,30
2,4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5.0,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g,30
3,5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,NaN,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g,82
4,10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5.0,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg,32

In [45]:
df.columns

Index(['Unnamed: 0', 'business_id', 'cool', 'date', 'funny', 'review_id',
       'stars', 'text', 'useful', 'user_id', 'review.length'],
      dtype='object')

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2610 entries, 0 to 2609
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     2610 non-null   int64
 1   business_id    2610 non-null   object
 2   cool           2608 non-null   object
 3   date           2610 non-null   object
 4   funny          2610 non-null   int64
 5   review_id      2610 non-null   object
 6   stars          2607 non-null   float64
 7   text           2610 non-null   object
 8   useful         2610 non-null   int64
 9   user_id        2610 non-null   object
 10  review.length  2610 non-null   int64
dtypes: float64(1), int64(4), object(6)
memory usage: 224.4+ KB

In [55]:
df.duplicates()

AttributeError: 'DataFrame' object has no attribute 'duplicates'

In [ ]:
df.duplicated() .sum()  #this are duplicated rows

333

In [ ]:
df.duplicated() .value_counts() # this are  ones that are duplicated and not duplicated

False    2277
True      333
dtype: int64

In [ ]:
df[df.duplicated()].head() #basically the first five rows

,Unnamed: 0,business_id,cool,date,funny,review_id,stars,text,useful,user_id,review.length
1411,4252,fIuquIgWrkNEM5yvYSHPgw,2,2014-08-05,0,X4glBKsOvs6fgjHNJ0IUjw,5.0,What a compassionate and thorough professional...,3,xDjaGtx-TZUDdUxRKJnKCA,72
1412,3028,_JD_U3pZDynB6l8swzVlQA,0,2017-12-17,0,iuVHqEglBCmL1lAbw8B2Ow,5.0,Had to switch barbers because I moved and the ...,0,WBKGxL53Tcq2_CkPavBYQA,93
1414,3046,yQUXMWSA8H7wvkLa4iCD8g,0,2014-08-28,0,KmKCR_cHmAYA12Uy3XPHCA,2.0,Rude waitress and slow service. No offers for ...,1,KeYB7tU5F5PFb7X1QoWJ6Q,78
1417,2322,1lLJDy73uBp_I2LJ0B0Fkw,1,2011-09-09,0,03dNKEDriDeZ8poYbiNyxQ,5.0,Was here for a party last weekend and had a bl...,0,ftLmo96CeyaNcVqHleDSHw,27
1419,794,XXW_OFaYQkkGOGniujZFHg,0,2013-12-04,0,XxsMdJl8OTgeq5iEhp4JLQ,5.0,this is for the fireside lounge.\r\ngreat plac...,1,D1_nrBr4dOrs7M82OaBRwQ,37

In [62]:
df=df.drop_duplicates()

In [63]:
df.duplicated() .value_counts()

False    2277
dtype: int64