In [43]:
import pandas as pd

In [44]:
df=pd.read_csv('data/titanic.csv')

In [45]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1.0,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,NaN,S
1,2.0,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,C85,C
2,3.0,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,NaN,S
3,4.0,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,C123,S
4,5.0,0.0,3,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,NaN,S

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1391 entries, 0 to 1390
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1391 non-null   float64
 1   Survived     1391 non-null   float64
 2   Pclass       1391 non-null   object
 3   Name         1391 non-null   object
 4   Sex          1391 non-null   object
 5   Age          1209 non-null   float64
 6   SibSp        1391 non-null   float64
 7   Parch        1391 non-null   float64
 8   Ticket       1391 non-null   object
 9   Fare         1391 non-null   float64
 10  Cabin        602 non-null    object
 11  Embarked     1289 non-null   object
dtypes: float64(6), object(6)
memory usage: 130.5+ KB

In [47]:
df.shape

(1391, 12)

In [48]:
#df.dropna(axis=1,inplace=True) #it drops all columns that have missing values but in case of axis=0 it drops all rows
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1391 entries, 0 to 1390
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1391 non-null   float64
 1   Survived     1391 non-null   float64
 2   Pclass       1391 non-null   object
 3   Name         1391 non-null   object
 4   Sex          1391 non-null   object
 5   Age          1209 non-null   float64
 6   SibSp        1391 non-null   float64
 7   Parch        1391 non-null   float64
 8   Ticket       1391 non-null   object
 9   Fare         1391 non-null   float64
 10  Cabin        602 non-null    object
 11  Embarked     1289 non-null   object
dtypes: float64(6), object(6)
memory usage: 130.5+ KB

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1.0,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,NaN,S
1,2.0,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,C85,C
2,3.0,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,NaN,S
3,4.0,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,C123,S
4,5.0,0.0,3,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,NaN,S

In [49]:
df.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1386,False,False,False,False,False,False,False,False,False,False,False,False
1387,False,False,False,False,False,False,False,False,False,False,False,True
1388,False,False,False,False,False,False,False,False,False,False,False,True
1389,False,False,False,False,False,False,False,False,False,False,False,False
1390,False,False,False,False,False,False,False,False,False,False,False,False

In [50]:
#basically used to calculate  null values 
#isnull
df.isna() .sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            182
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          789
Embarked       102
dtype: int64

In [51]:
df = df.drop("Cabin", axis=1)    #it has been affected by the dropna scenario

In [52]:
df.isna() .sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            182
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked       102
dtype: int64

In [53]:
df.isna() .sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            182
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked       102
dtype: int64

In [55]:
age_medium= df["Age"] .median()
age_medium

27.0

In [56]:
df["Age"]= df["Age"] .fillna(age_medium)

In [57]:
df.isna() . sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked       102
dtype: int64

In [60]:
df.head(30)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1.0,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,S
1,2.0,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,C
2,3.0,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,S
3,4.0,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,S
4,5.0,0.0,3,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,S
5,6.0,0.0,3,"Moran, Mr. James",male,27.0,0.0,0.0,330877,8.4583,Q
6,7.0,0.0,1,"McCarthy, Mr. Timothy J",male,54.0,0.0,0.0,17463,51.8625,S
7,8.0,0.0,3,"Palsson, Master. Gosta Leonard",male,2.0,3.0,1.0,349909,21.0750,S
8,9.0,1.0,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0.0,2.0,347742,11.1333,S
9,10.0,1.0,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1.0,0.0,237736,30.0708,C
10,11.0,1.0,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1.0,1.0,PP 9549,16.7000,S
11,12.0,1.0,1,"Bonnell, Miss. Elizabeth",female,58.0,0.0,0.0,113783,26.5500,S
12,13.0,0.0,3,"Saundercock, Mr. William Henry",male,20.0,0.0,0.0,A/5. 2151,8.0500,S
13,14.0,0.0,3,"Andersson, Mr. Anders Johan",male,39.0,1.0,5.0,347082,31.2750,S
14,15.0,0.0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0.0,0.0,350406,7.8542,S
15,16.0,1.0,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0.0,0.0,248706,16.0000,S
16,17.0,0.0,3,"Rice, Master. Eugene",male,2.0,4.0,1.0,382652,29.1250,Q
17,18.0,1.0,2,"Williams, Mr. Charles Eugene",male,27.0,0.0,0.0,244373,13.0000,S
18,19.0,0.0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1.0,0.0,345763,18.0000,S
19,20.0,1.0,3,"Masselmani, Mrs. Fatima",female,27.0,0.0,0.0,2649,7.2250,C
20,21.0,0.0,2,"Fynney, Mr. Joseph J",male,35.0,0.0,0.0,239865,26.0000,S
21,22.0,1.0,2,"Beesley, Mr. Lawrence",male,34.0,0.0,0.0,248698,13.0000,S
22,23.0,1.0,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0.0,0.0,330923,8.0292,Q
23,24.0,1.0,1,"Sloper, Mr. William Thompson",male,28.0,0.0,0.0,113788,35.5000,S
24,25.0,0.0,3,"Palsson, Miss. Torborg Danira",female,8.0,3.0,1.0,349909,21.0750,S
25,26.0,1.0,?,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1.0,5.0,347077,31.3875,S
26,27.0,0.0,3,"Emir, Mr. Farred Chehab",male,27.0,0.0,0.0,2631,7.2250,C
27,28.0,0.0,1,"Fortune, Mr. Charles Alexander",male,19.0,3.0,2.0,19950,263.0000,S
28,29.0,1.0,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,27.0,0.0,0.0,330959,7.8792,Q
29,30.0,0.0,3,"Todoroff, Mr. Lalio",male,27.0,0.0,0.0,349216,7.8958,S

In [61]:
df["Embarked"] .value_counts()

S    830
C    285
Q    174
Name: Embarked, dtype: int64

In [62]:
embarked_mode = df["Embarked"].mode()
embarked_mode

0    S
Name: Embarked, dtype: object

In [63]:
df["Embarked"] = df["Embarked"].fillna(embarked_mode[0])

In [64]:
df.isna() .sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [ ]:
#ffffffffffffff